version: '3.8'

networks:
  laravel:
    name: laravel
    
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  php:
    image: php:8.0.16-fpm-alpine3.14
    container_name: php
    networks:
      - laravel

  mysql:
    image: mysql:8.0.28
    container_name: mysql
    environment:
      MYSQL_DATABASE: laraveldb
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel